server:
  port: 8840

spring:
  application:
    name: nacos-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
